import { Resource } from './types';

export const resources: Resource[] = [
  // Succeed in Classes
  {
    id: 'writing-place',
    title: 'The Writing Place',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Feedback on papers and writing assignments. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Appointment', 'Academic'],
    link: 'https://www.writing.northwestern.edu/',
  },
  {
    id: 'academic-support',
    title: 'Academic Support & Learning Advancement',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Tutoring + study strategies for hard classes. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Tutoring', 'Academic'],
    link: 'https://www.northwestern.edu/academic-support-learning/',
  },
  {
    id: 'accessible-nu',
    title: 'AccessibleNU',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Disability accommodations and academic access support. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Confidential', 'Academic Support'],
    link: 'https://www.northwestern.edu/accessiblenu/',
  },
  {
    id: 'peer-guided-study',
    title: 'Peer-Guided Study Groups',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Weekly study sessions for challenging STEM courses. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Peer Learning', 'STEM'],
    link: 'https://www.northwestern.edu/academic-support-learning/course-support/peer-guided-study-groups/',
  },
  {
    id: 'canvas',
    title: 'Canvas Learning Management System',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Access course materials, assignments, and grades. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Online', 'Required', 'Academic'],
    link: 'https://canvas.northwestern.edu/',
  },
  {
    id: 'library-research',
    title: 'University Library Research Help',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Research support and librarian consultations for projects. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Appointment', 'Research', 'Academic'],
    link: 'https://www.library.northwestern.edu/',
  },
  {
    id: 'office-hours',
    title: 'Professor & TA Office Hours',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Direct help from instructors on course material. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Academic', 'In-person'],
    link: 'https://history.northwestern.edu/undergraduate/teaching-assistant-office-hours.html',
  },

  // Career & Internships
  {
    id: 'nca',
    title: 'Northwestern Career Advancement (NCA)',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Resume reviews, career advising, and internship planning. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Appointment', 'Career'],
    link: 'https://www.northwestern.edu/careers/',
  },
  {
    id: 'handshake',
    title: 'Handshake',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Search and apply for internships/jobs. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Online', 'Job Search'],
    link: 'https://www.northwestern.edu/careers/resources/handshake-access.html',
  },
  {
    id: 'vmock',
    title: 'VMock',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'AI resume feedback and scoring. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Online', 'Career Tool'],
    link: 'https://www.northwestern.edu/careers/jobs-internships/resumes/vmock.html',
  },
  {
    id: 'linkedin-learning',
    title: 'LinkedIn Learning',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Free courses on professional skills and software. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Online', 'Free', 'Skill Building'],
    link: 'https://hr.northwestern.edu/talent-development/development/online-learning/lynda.com.html',
  },
  {
    id: 'big-interview',
    title: 'Big Interview',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Practice interviews with AI feedback. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Online', 'Career Tool', 'Interview Prep'],
    link: 'https://www.northwestern.edu/careers/jobs-internships/interviewing/',
  },
  {
    id: 'career-fairs',
    title: 'Career Fairs & Networking Events',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Meet employers and explore career opportunities. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Networking', 'Career'],
    link: 'https://www.northwestern.edu/careers/programs-opportunities/career-fairs-at-northwestern.html',
  },
  {
    id: 'alumni-network',
    title: 'Northwestern Alumni Network',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Connect with alumni for career advice and mentorship. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Networking', 'Mentorship', 'Career'],
    link: 'https://alumni.northwestern.edu/',
  },

  // Health & Wellbeing
  {
    id: 'caps',
    title: 'CAPS Counseling',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Confidential mental health counseling and support. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Confidential', 'Mental Health', 'Appointment'],
    link: 'https://www.northwestern.edu/counseling/',
  },
  {
    id: 'student-health',
    title: 'Student Health Services',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Medical care and health appointments. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Appointment'],
    link: 'https://www.northwestern.edu/healthservice-evanston/',
  },
  {
    id: 'recreation',
    title: 'Campus Recreation',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Gym access, fitness classes, wellness programs. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Fitness'],
    link: 'https://nurecreation.com/',
  },
  {
    id: 'timely-care',
    title: 'TimelyCare (24/7 Telehealth)',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Free 24/7 virtual medical and mental health visits. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['24/7', 'Online', 'Mental Health', 'Medical'],
    link: 'https://www.northwestern.edu/nuhelp/self-care/timelycare/',
  },
  {
    id: 'peer-health',
    title: 'Peer Health Exchange',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Peer-led wellness workshops and support. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Peer Support', 'Wellness', 'Free'],
    link: 'https://www.instagram.com/northwestern_phe/',
  },
  {
    id: 'sexual-health',
    title: 'Sexual Health & Assault Resources',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Confidential support and resources for sexual health. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Confidential', '24/7', 'Support'],
    link: 'https://www.northwestern.edu/csaw/resources/sexual-health/',
  },
  {
    id: 'nutrition',
    title: 'Nutrition Counseling',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'One-on-one nutrition and eating support. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Appointment', 'Confidential', 'Wellness'],
    link: 'https://www.nm.org/conditions-and-care-areas/treatments/nutritional-counseling',
  },
  {
    id: 'mindfulness',
    title: 'Mindfulness & Meditation Programs',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Free meditation sessions and stress relief workshops. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Wellness', 'Mental Health'],
    link: 'https://www.northwestern.edu/csaw/programming/mindfulness-based-stress-reduction-mbsr.html',
  },

  // Safety
  {
    id: 'nupd',
    title: 'Northwestern University Police',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Emergency response and campus policing. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Emergency', '24/7'],
    link: 'https://www.northwestern.edu/up/',
  },
  {
    id: 'safe-ride',
    title: 'Safe Ride / Escort Services',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Late-night ride or safety escort. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Night Service'],
    link: 'https://www.northwestern.edu/up/',
  },
  {
    id: 'wildcard',
    title: 'Wildcard (Campus ID)',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Access buildings and services securely. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Required', 'Campus Access'],
    link: 'https://www.northwestern.edu/norris/services/wildcard/',
  },
  {
    id: 'rave-guardian',
    title: 'Rave Guardian Safety App',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Mobile safety timer and emergency contact app. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Mobile App', 'Free', 'Safety'],
    link: 'https://www.northwestern.edu/up/',
  },
  {
    id: 'blue-phones',
    title: 'Emergency Blue Light Phones',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Campus-wide emergency call boxes. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Emergency', 'In-person', '24/7'],
    link: 'https://www.northwestern.edu/up/',
  },

  // Tech & Software
  {
    id: 'microsoft-365',
    title: 'Microsoft 365',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Word/Excel/PowerPoint access for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Online'],
    link: 'https://www.it.northwestern.edu/software/',
  },
  {
    id: 'adobe',
    title: 'Adobe Creative Cloud',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Photoshop/Illustrator and other Adobe apps. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Design'],
    link: 'https://www.it.northwestern.edu/software/',
  },
  {
    id: 'it-help',
    title: 'IT Help Desk',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Help with Wi-Fi, accounts, software issues. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Support', 'In-person', 'Online'],
    link: 'https://www.it.northwestern.edu/support/',
  },
  {
    id: 'matlab',
    title: 'MATLAB',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Engineering and scientific computing software. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'STEM', 'Engineering'],
    link: 'https://www.it.northwestern.edu/software/',
  },
  {
    id: 'zoom',
    title: 'Zoom Pro',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Video conferencing for classes and group work. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Online', 'Communication'],
    link: 'https://www.it.northwestern.edu/software/',
  },
  {
    id: 'google-workspace',
    title: 'Google Workspace',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Gmail, Drive, Docs, and collaboration tools. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Online', 'Collaboration'],
    link: 'https://www.it.northwestern.edu/software/',
  },
  {
    id: 'vpn',
    title: 'Northwestern VPN',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Secure access to campus resources from anywhere. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Security', 'Remote Access'],
    link: 'https://www.it.northwestern.edu/software/',
  },
  {
    id: 'github-education',
    title: 'GitHub Student Developer Pack',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Free developer tools and cloud credits. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Development', 'Online'],
    link: 'https://education.github.com/',
  },
  {
    id: 'spss',
    title: 'SPSS Statistics',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Statistical analysis software for research. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Research', 'Data Analysis'],
    link: 'https://www.it.northwestern.edu/software/',
  },

  // Money, Food, & Housing
  {
    id: 'food-pantry',
    title: 'Campus Food Pantry',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Free groceries and food support. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free', 'Food Support'],
    link: 'https://www.northwestern.edu/basic-needs/food-security/',
  },
  {
    id: 'emergency-aid',
    title: 'Emergency Financial Aid',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Short-term support for unexpected hardship. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Confidential', 'Financial Support'],
    link: 'https://www.northwestern.edu/financial-aid/undergraduate/aid-programs/emergency-aid.html',
  },
  {
    id: 'financial-aid',
    title: 'Financial Aid Office',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Scholarships, loans, and financial planning help. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Appointment', 'Financial Support', 'Scholarships'],
    link: 'https://www.northwestern.edu/financial-aid/',
  },
  {
    id: 'meal-plans',
    title: 'Dining Services & Meal Plans',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Campus dining options and meal plan management. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Food Support', 'In-person', 'Required'],
    link: 'https://www.northwestern.edu/dining/',
  },
  {
    id: 'housing',
    title: 'Residential Services',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'On-campus housing support and roommate matching. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Housing', 'In-person', 'Support'],
    link: 'https://www.northwestern.edu/living/',
  },
  {
    id: 'off-campus-housing',
    title: 'Off-Campus Housing Resources',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Help finding apartments and understanding leases. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Housing', 'Online', 'Off-campus'],
    link: 'https://offcampus.northwestern.edu/',
  },
  {
    id: 'student-employment',
    title: 'Student Employment Office',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Find on-campus jobs and work-study positions. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Job Search', 'Financial Support', 'On-campus'],
    link: 'https://www.northwestern.edu/studentemployment/',
  },

  // Community & Student Life
  {
    id: 'wildcat-connection',
    title: 'Wildcat Connection',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Find and join student organizations. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Student Orgs', 'Community'],
    link: 'https://northwestern.campuslabs.com/engage/',
  },
  {
    id: 'norris',
    title: 'Norris University Center',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Student center with dining, events, and meeting spaces. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Events', 'Community'],
    link: 'https://www.northwestern.edu/norris/',
  },
  {
    id: 'multicultural-centers',
    title: 'Multicultural Student Affairs',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Cultural centers and identity-based community support. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Community', 'Support', 'Diversity'],
    link: 'https://www.northwestern.edu/msa/',
  },
  {
    id: 'religious-life',
    title: 'Religious & Spiritual Life',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Faith-based communities and spiritual resources. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Community', 'Spiritual', 'Support'],
    link: 'https://www.northwestern.edu/religious-life/',
  },
  {
    id: 'greek-life',
    title: 'Fraternity & Sorority Life',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Greek organizations and recruitment information. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Community', 'Social', 'Student Orgs'],
    link: 'https://www.northwestern.edu/fsl/',
  },
  {
    id: 'arts-events',
    title: 'Arts & Entertainment Events',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Concerts, theater, galleries, and performances. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Events', 'Arts', 'Free'],
    link: 'https://planitpurple.northwestern.edu/',
  },
  {
    id: 'athletics',
    title: 'Northwestern Athletics',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Varsity sports, club teams, and intramurals. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Sports', 'Recreation', 'In-person'],
    link: 'https://nusports.com/',
  },
  {
    id: 'volunteer',
    title: 'Volunteer & Community Service',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Service opportunities and volunteer programs. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Community Service', 'Volunteer', 'Events'],
    link: 'https://www.northwestern.edu/civic-engagement/',
  },

  // Spaces & Facilities
  {
    id: 'study-rooms',
    title: 'Reservable Study Rooms',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Book group or quiet study spaces. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Reservation'],
    link: 'https://www.library.northwestern.edu/visit/study-spaces/',
  },
  {
    id: 'libraries',
    title: 'University Libraries',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Multiple library locations for study and research. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Study Space', '24/7'],
    link: 'https://www.library.northwestern.edu/',
  },
  {
    id: 'makerspace',
    title: 'The Garage (Makerspace)',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: '3D printing, laser cutting, and prototyping tools. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Innovation', 'In-person', 'Making'],
    link: 'https://www.northwestern.edu/thegarage/',
  },
  {
    id: 'computer-labs',
    title: 'Computer Labs',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Free computers with specialized software. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Technology', 'Free'],
    link: 'https://www.it.northwestern.edu/services/labs/',
  },
  {
    id: 'music-practice',
    title: 'Music Practice Rooms',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Reserve practice spaces with instruments. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Arts', 'Reservation'],
    link: 'https://www.music.northwestern.edu/resources/practice-rooms.html',
  },
  {
    id: 'meeting-rooms',
    title: 'Student Group Meeting Spaces',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Book rooms for club meetings and events. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Reservation', 'Student Orgs'],
    link: 'https://www.northwestern.edu/norris/reservations/',
  },
  {
    id: 'lakefill',
    title: 'Lakefill & Outdoor Spaces',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Beautiful outdoor areas for study and relaxation. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['In-person', 'Outdoor', 'Free'],
    link: 'https://www.northwestern.edu/recreation/facilities/lakefill.html',
  },

  // Student Life & Events
  {
    id: 'dillo-day',
    title: 'Dillo Day',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Annual spring music festival on the Lakefill, the largest student-run event in the nation. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Festival', 'Music', 'Annual Event', 'Free'],
    link: 'https://www.dilloday.com/',
  },
  {
    id: 'dance-marathon',
    title: 'Dance Marathon (NUDM)',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: '30-hour philanthropy event raising funds for children\'s hospitals. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Philanthropy', 'Annual Event', 'Community'],
    link: 'https://www.nudm.org/',
  },
  {
    id: 'homecoming',
    title: 'Homecoming Week',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Week of traditions including the parade, pep rally, and football game. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Annual Event', 'Tradition', 'Sports'],
    link: 'https://www.northwestern.edu/homecoming/',
  },
  {
    id: 'wildcat-welcome',
    title: 'Wildcat Welcome',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'New student orientation and week of welcome events each fall. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Orientation', 'New Students', 'Annual Event'],
    link: 'https://www.northwestern.edu/orientation/',
  },
  {
    id: 'mayfest',
    title: 'Mayfest',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Student organization that plans Dillo Day and spring activities. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Student Orgs', 'Events', 'Programming'],
    link: 'https://www.mayfestproductions.org/',
  },
  {
    id: 'armadillo-day',
    title: 'Armadillo Day',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Free fall concert and festival on the Lakefill. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Festival', 'Music', 'Annual Event', 'Free'],
    link: 'https://www.northwestern.edu/norris/armadillo-day/',
  },
  {
    id: 'a-e-productions',
    title: 'A&E Productions',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Student board bringing concerts, comedians, and entertainment to campus. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Student Orgs', 'Events', 'Entertainment'],
    link: 'https://www.aeproductions.org/',
  },
  {
    id: 'winter-formal',
    title: 'Winter Formal',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Annual semi-formal dance event in winter quarter. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Social', 'Annual Event', 'Dance'],
    link: 'https://www.northwestern.edu/norris/winter-formal/',
  },
  {
    id: 'primal-scream',
    title: 'Primal Scream',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Finals week tradition of screaming together at 9pm to relieve stress. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Tradition', 'Stress Relief', 'Community'],
    link: 'https://www.northwestern.edu/norris/primal-scream/',
  },
  {
    id: 'block-seating',
    title: 'Block Seating (Football Games)',
    category: 'Student Life & Events',
    categoryBlurb: 'Campus traditions, festivals, and student-run events.',
    description: 'Free student section tickets for Northwestern football games. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Sports', 'Free', 'In-person'],
    link: 'https://nusports.com/sports/2015/7/17/GEN_20140101146.aspx',
  },

  // Professional Fraternities
  {
    id: 'delta-sigma-pi',
    title: 'Delta Sigma Pi (DSP)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Professional business fraternity focused on networking and career development. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Business', 'Networking', 'Professional Development'],
    link: 'https://northwestern.campuslabs.com/engage/organization/deltasigmapi',
  },
  {
    id: 'alpha-kappa-psi',
    title: 'Alpha Kappa Psi (AKPsi)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Professional business fraternity emphasizing leadership and service. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Business', 'Leadership', 'Professional Development'],
    link: 'https://northwestern.campuslabs.com/engage/organization/alphakappapsi',
  },
  {
    id: 'phi-alpha-delta',
    title: 'Phi Alpha Delta (PAD)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Pre-law professional fraternity for students interested in legal careers. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Pre-Law', 'Legal', 'Professional Development'],
    link: 'https://northwestern.campuslabs.com/engage/organization/phialphadelta',
  },
  {
    id: 'alpha-phi-omega',
    title: 'Alpha Phi Omega (APO)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Co-ed service fraternity focused on leadership, friendship, and service. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Service', 'Leadership', 'Community Service'],
    link: 'https://northwestern.campuslabs.com/engage/organization/alphaphiomega',
  },
  {
    id: 'theta-tau',
    title: 'Theta Tau',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Professional engineering fraternity for engineering students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Engineering', 'Professional Development', 'STEM'],
    link: 'https://northwestern.campuslabs.com/engage/organization/thetatau',
  },
  {
    id: 'delta-epsilon-mu',
    title: 'Delta Epsilon Mu (DEM)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Pre-health professional fraternity for students pursuing medical careers. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Pre-Med', 'Health', 'Professional Development'],
    link: 'https://northwestern.campuslabs.com/engage/organization/deltaepsilonmu',
  },
  {
    id: 'phi-delta-epsilon',
    title: 'Phi Delta Epsilon (PhiDE)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'International medical fraternity promoting excellence in healthcare. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Pre-Med', 'Medical', 'Professional Development'],
    link: 'https://northwestern.campuslabs.com/engage/organization/phideltaepsilon',
  },
  {
    id: 'kappa-theta-pi',
    title: 'Kappa Theta Pi (KTP)',
    category: 'Professional Fraternities',
    categoryBlurb: 'Co-ed business and professional development organizations.',
    description: 'Professional technology fraternity for students in tech and entrepreneurship. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Technology', 'Entrepreneurship', 'Professional Development'],
    link: 'https://northwestern.campuslabs.com/engage/organization/kappathetapi',
  },

  // Northwestern Affiliated or Sponsored Licensing
  {
    id: 'jetbrains',
    title: 'JetBrains IDEs (IntelliJ, PyCharm, etc.)',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free professional development tools for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Development', 'IDE'],
    link: 'https://www.jetbrains.com/community/education/',
  },
  {
    id: 'autodesk',
    title: 'Autodesk Education (AutoCAD, Fusion 360)',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free CAD and 3D modeling software for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Design', 'Engineering'],
    link: 'https://www.autodesk.com/education/home',
  },
  {
    id: 'spotify-premium',
    title: 'Spotify Premium Student',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Discounted music streaming for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Student Discount', 'Entertainment', 'Subscription'],
    link: 'https://www.spotify.com/student/',
  },
  {
    id: 'apple-music',
    title: 'Apple Music Student',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Discounted Apple Music subscription for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Student Discount', 'Entertainment', 'Subscription'],
    link: 'https://www.apple.com/apple-music/',
  },
  {
    id: 'amazon-prime',
    title: 'Amazon Prime Student',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Discounted Prime membership with free shipping and streaming. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Student Discount', 'Shopping', 'Subscription'],
    link: 'https://www.amazon.com/studentprime',
  },
  {
    id: 'tableau',
    title: 'Tableau for Students',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free data visualization software for academic use. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Data Analysis', 'Visualization'],
    link: 'https://www.tableau.com/academic/students',
  },
  {
    id: 'canva-pro',
    title: 'Canva Pro for Education',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free premium design tools for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Design', 'Online'],
    link: 'https://www.canva.com/education/',
  },
  {
    id: 'notion',
    title: 'Notion Education Plan',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free productivity and note-taking workspace for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Productivity', 'Online'],
    link: 'https://www.notion.so/students',
  },
  {
    id: 'aws-educate',
    title: 'AWS Educate',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free cloud computing credits and training for students. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Cloud Computing', 'Development'],
    link: 'https://aws.amazon.com/education/awseducate/',
  },
  {
    id: 'figma-education',
    title: 'Figma for Education',
    category: 'Northwestern Affiliated or Sponsored Licensing',
    categoryBlurb: 'Student discounts on software, services, and subscriptions.',
    description: 'Free professional design and prototyping tools. Learn more about eligibility, hours, and access details on the official page.',
    tags: ['Free Software', 'Design', 'Collaboration'],
    link: 'https://www.figma.com/education/ Learn more about eligibility, hours, and access details on the official page.',
  },
];
