import { Resource } from './types';

export const resources: Resource[] = [
  // Succeed in Classes
  {
    id: 'writing-place',
    title: 'The Writing Place',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Feedback on papers and writing assignments.',
    tags: ['Free', 'Appointment', 'Academic'],
    link: '#',
  },
  {
    id: 'academic-support',
    title: 'Academic Support & Learning Advancement',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Tutoring + study strategies for hard classes.',
    tags: ['Free', 'Tutoring', 'Academic'],
    link: '#',
  },
  {
    id: 'accessible-nu',
    title: 'AccessibleNU',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Disability accommodations and academic access support.',
    tags: ['Confidential', 'Academic Support'],
    link: '#',
  },
  {
    id: 'peer-guided-study',
    title: 'Peer-Guided Study Groups',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Weekly study sessions for challenging STEM courses.',
    tags: ['Free', 'Peer Learning', 'STEM'],
    link: '#',
  },
  {
    id: 'canvas',
    title: 'Canvas Learning Management System',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Access course materials, assignments, and grades.',
    tags: ['Online', 'Required', 'Academic'],
    link: 'https://canvas.northwestern.edu/',
  },
  {
    id: 'library-research',
    title: 'University Library Research Help',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Research support and librarian consultations for projects.',
    tags: ['Appointment', 'Research', 'Academic'],
    link: 'https://www.library.northwestern.edu/',
  },
  {
    id: 'office-hours',
    title: 'Professor & TA Office Hours',
    category: 'Succeed in Classes',
    categoryBlurb: 'Academic support, tutoring, and accommodations.',
    description: 'Direct help from instructors on course material.',
    tags: ['Free', 'Academic', 'In-person'],
    link: '#',
  },

  // Career & Internships
  {
    id: 'nca',
    title: 'Northwestern Career Advancement (NCA)',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Resume reviews, career advising, and internship planning.',
    tags: ['Appointment', 'Career'],
    link: '#',
  },
  {
    id: 'handshake',
    title: 'Handshake',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Search and apply for internships/jobs.',
    tags: ['Online', 'Job Search'],
    link: '#',
  },
  {
    id: 'vmock',
    title: 'VMock',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'AI resume feedback and scoring.',
    tags: ['Online', 'Career Tool'],
    link: '#',
  },
  {
    id: 'linkedin-learning',
    title: 'LinkedIn Learning',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Free courses on professional skills and software.',
    tags: ['Online', 'Free', 'Skill Building'],
    link: '#',
  },
  {
    id: 'big-interview',
    title: 'Big Interview',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Practice interviews with AI feedback.',
    tags: ['Online', 'Career Tool', 'Interview Prep'],
    link: '#',
  },
  {
    id: 'career-fairs',
    title: 'Career Fairs & Networking Events',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Meet employers and explore career opportunities.',
    tags: ['In-person', 'Networking', 'Career'],
    link: '#',
  },
  {
    id: 'alumni-network',
    title: 'Northwestern Alumni Network',
    category: 'Career & Internships',
    categoryBlurb: 'Resumes, advising, and job searching tools.',
    description: 'Connect with alumni for career advice and mentorship.',
    tags: ['Networking', 'Mentorship', 'Career'],
    link: '#',
  },

  // Health & Wellbeing
  {
    id: 'caps',
    title: 'CAPS Counseling',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Confidential mental health counseling and support.',
    tags: ['Confidential', 'Mental Health', 'Appointment'],
    link: '#',
  },
  {
    id: 'student-health',
    title: 'Student Health Services',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Medical care and health appointments.',
    tags: ['In-person', 'Appointment'],
    link: '#',
  },
  {
    id: 'recreation',
    title: 'Campus Recreation',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Gym access, fitness classes, wellness programs.',
    tags: ['In-person', 'Fitness'],
    link: '#',
  },
  {
    id: 'timely-care',
    title: 'TimelyCare (24/7 Telehealth)',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Free 24/7 virtual medical and mental health visits.',
    tags: ['24/7', 'Online', 'Mental Health', 'Medical'],
    link: '#',
  },
  {
    id: 'peer-health',
    title: 'Peer Health Exchange',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Peer-led wellness workshops and support.',
    tags: ['Peer Support', 'Wellness', 'Free'],
    link: '#',
  },
  {
    id: 'sexual-health',
    title: 'Sexual Health & Assault Resources',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Confidential support and resources for sexual health.',
    tags: ['Confidential', '24/7', 'Support'],
    link: '#',
  },
  {
    id: 'nutrition',
    title: 'Nutrition Counseling',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'One-on-one nutrition and eating support.',
    tags: ['Appointment', 'Confidential', 'Wellness'],
    link: '#',
  },
  {
    id: 'mindfulness',
    title: 'Mindfulness & Meditation Programs',
    category: 'Health & Wellbeing',
    categoryBlurb: 'Mental health, medical care, and wellness.',
    description: 'Free meditation sessions and stress relief workshops.',
    tags: ['Free', 'Wellness', 'Mental Health'],
    link: '#',
  },

  // Safety
  {
    id: 'nupd',
    title: 'Northwestern University Police',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Emergency response and campus policing.',
    tags: ['Emergency', '24/7'],
    link: '#',
  },
  {
    id: 'safe-ride',
    title: 'Safe Ride / Escort Services',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Late-night ride or safety escort.',
    tags: ['Free', 'Night Service'],
    link: '#',
  },
  {
    id: 'wildcard',
    title: 'Wildcard (Campus ID)',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Access buildings and services securely.',
    tags: ['Required', 'Campus Access'],
    link: '#',
  },
  {
    id: 'rave-guardian',
    title: 'Rave Guardian Safety App',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Mobile safety timer and emergency contact app.',
    tags: ['Mobile App', 'Free', 'Safety'],
    link: '#',
  },
  {
    id: 'blue-phones',
    title: 'Emergency Blue Light Phones',
    category: 'Safety',
    categoryBlurb: 'Emergency support and late-night safety tools.',
    description: 'Campus-wide emergency call boxes.',
    tags: ['Emergency', 'In-person', '24/7'],
    link: '#',
  },

  // Tech & Software
  {
    id: 'microsoft-365',
    title: 'Microsoft 365',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Word/Excel/PowerPoint access for students.',
    tags: ['Free Software', 'Online'],
    link: '#',
  },
  {
    id: 'adobe',
    title: 'Adobe Creative Cloud',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Photoshop/Illustrator and other Adobe apps.',
    tags: ['Free Software', 'Design'],
    link: '#',
  },
  {
    id: 'it-help',
    title: 'IT Help Desk',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Help with Wi-Fi, accounts, software issues.',
    tags: ['Support', 'In-person', 'Online'],
    link: '#',
  },
  {
    id: 'matlab',
    title: 'MATLAB',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Engineering and scientific computing software.',
    tags: ['Free Software', 'STEM', 'Engineering'],
    link: '#',
  },
  {
    id: 'zoom',
    title: 'Zoom Pro',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Video conferencing for classes and group work.',
    tags: ['Free Software', 'Online', 'Communication'],
    link: '#',
  },
  {
    id: 'google-workspace',
    title: 'Google Workspace',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Gmail, Drive, Docs, and collaboration tools.',
    tags: ['Free Software', 'Online', 'Collaboration'],
    link: '#',
  },
  {
    id: 'vpn',
    title: 'Northwestern VPN',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Secure access to campus resources from anywhere.',
    tags: ['Free Software', 'Security', 'Remote Access'],
    link: '#',
  },
  {
    id: 'github-education',
    title: 'GitHub Student Developer Pack',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Free developer tools and cloud credits.',
    tags: ['Free Software', 'Development', 'Online'],
    link: 'https://education.github.com/',
  },
  {
    id: 'spss',
    title: 'SPSS Statistics',
    category: 'Tech & Software',
    categoryBlurb: 'Free software and IT help for coursework.',
    description: 'Statistical analysis software for research.',
    tags: ['Free Software', 'Research', 'Data Analysis'],
    link: '#',
  },

  // Money, Food, & Housing
  {
    id: 'food-pantry',
    title: 'Campus Food Pantry',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Free groceries and food support.',
    tags: ['Free', 'Food Support'],
    link: '#',
  },
  {
    id: 'emergency-aid',
    title: 'Emergency Financial Aid',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Short-term support for unexpected hardship.',
    tags: ['Confidential', 'Financial Support'],
    link: '#',
  },
  {
    id: 'financial-aid',
    title: 'Financial Aid Office',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Scholarships, loans, and financial planning help.',
    tags: ['Appointment', 'Financial Support', 'Scholarships'],
    link: '#',
  },
  {
    id: 'meal-plans',
    title: 'Dining Services & Meal Plans',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Campus dining options and meal plan management.',
    tags: ['Food Support', 'In-person', 'Required'],
    link: '#',
  },
  {
    id: 'housing',
    title: 'Residential Services',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'On-campus housing support and roommate matching.',
    tags: ['Housing', 'In-person', 'Support'],
    link: '#',
  },
  {
    id: 'off-campus-housing',
    title: 'Off-Campus Housing Resources',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Help finding apartments and understanding leases.',
    tags: ['Housing', 'Online', 'Off-campus'],
    link: '#',
  },
  {
    id: 'student-employment',
    title: 'Student Employment Office',
    category: 'Money, Food, & Housing',
    categoryBlurb: 'Support for financial stress and basic needs.',
    description: 'Find on-campus jobs and work-study positions.',
    tags: ['Job Search', 'Financial Support', 'On-campus'],
    link: '#',
  },

  // Community & Student Life
  {
    id: 'wildcat-connection',
    title: 'Wildcat Connection',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Find and join student organizations.',
    tags: ['Student Orgs', 'Community'],
    link: '#',
  },
  {
    id: 'norris',
    title: 'Norris University Center',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Student center with dining, events, and meeting spaces.',
    tags: ['In-person', 'Events', 'Community'],
    link: '#',
  },
  {
    id: 'multicultural-centers',
    title: 'Multicultural Student Affairs',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Cultural centers and identity-based community support.',
    tags: ['Community', 'Support', 'Diversity'],
    link: '#',
  },
  {
    id: 'religious-life',
    title: 'Religious & Spiritual Life',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Faith-based communities and spiritual resources.',
    tags: ['Community', 'Spiritual', 'Support'],
    link: '#',
  },
  {
    id: 'greek-life',
    title: 'Fraternity & Sorority Life',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Greek organizations and recruitment information.',
    tags: ['Community', 'Social', 'Student Orgs'],
    link: '#',
  },
  {
    id: 'arts-events',
    title: 'Arts & Entertainment Events',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Concerts, theater, galleries, and performances.',
    tags: ['Events', 'Arts', 'Free'],
    link: '#',
  },
  {
    id: 'athletics',
    title: 'Northwestern Athletics',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Varsity sports, club teams, and intramurals.',
    tags: ['Sports', 'Recreation', 'In-person'],
    link: '#',
  },
  {
    id: 'volunteer',
    title: 'Volunteer & Community Service',
    category: 'Community & Student Life',
    categoryBlurb: 'Finding groups, belonging, and involvement.',
    description: 'Service opportunities and volunteer programs.',
    tags: ['Community Service', 'Volunteer', 'Events'],
    link: '#',
  },

  // Spaces & Facilities
  {
    id: 'study-rooms',
    title: 'Reservable Study Rooms',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Book group or quiet study spaces.',
    tags: ['In-person', 'Reservation'],
    link: '#',
  },
  {
    id: 'libraries',
    title: 'University Libraries',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Multiple library locations for study and research.',
    tags: ['In-person', 'Study Space', '24/7'],
    link: 'https://www.library.northwestern.edu/',
  },
  {
    id: 'makerspace',
    title: 'The Garage (Makerspace)',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: '3D printing, laser cutting, and prototyping tools.',
    tags: ['Innovation', 'In-person', 'Making'],
    link: '#',
  },
  {
    id: 'computer-labs',
    title: 'Computer Labs',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Free computers with specialized software.',
    tags: ['In-person', 'Technology', 'Free'],
    link: '#',
  },
  {
    id: 'music-practice',
    title: 'Music Practice Rooms',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Reserve practice spaces with instruments.',
    tags: ['In-person', 'Arts', 'Reservation'],
    link: '#',
  },
  {
    id: 'meeting-rooms',
    title: 'Student Group Meeting Spaces',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Book rooms for club meetings and events.',
    tags: ['In-person', 'Reservation', 'Student Orgs'],
    link: '#',
  },
  {
    id: 'lakefill',
    title: 'Lakefill & Outdoor Spaces',
    category: 'Spaces & Facilities',
    categoryBlurb: 'Places to study, create, and collaborate.',
    description: 'Beautiful outdoor areas for study and relaxation.',
    tags: ['In-person', 'Outdoor', 'Free'],
    link: '#',
  },
];
